import type { Pool, Pools } from '@/data/liquipedia/pools';
import { useLocalState } from '@/lib/storage';

/**
 * The event mode: play the whole site as one tournament's field.
 *
 * The week the Globals are on, every game should be about the Globals. That is
 * a mood you are in for a session, not a dropdown you re-pick in each of ten
 * games — so the choice is made once, on the home page, and every game reads it
 * from here.
 *
 * While a mode is in force the games stop offering region, difficulty and
 * status. Not because those controls are awkward to draw next to a field of
 * eighty, but because they are meaningless against one: "Globals, Asia, Hard"
 * leaves three players, and a difficulty band cut against five thousand rows
 * says nothing useful about eighty people who all qualified for the same event.
 *
 * `null` is the whole scene, and is the default.
 */

const KEY = 'event-mode';

export function useEventMode(): [string | null, (next: string | null) => void] {
  return useLocalState<string | null>(KEY, null);
}

/**
 * The mode's own pool, or null when it names one the data no longer has.
 *
 * Worth being careful about: the id is remembered in the browser and the pools
 * are regenerated by the notebook, so a mode can outlive the event it names.
 * Every caller treats a missing pool as "no mode", which is the same state a
 * fresh visitor is in.
 */
export function activePool(pools: Pools | null, event: string | null): Pool | null {
  return pools?.get(event) ?? null;
}
