import type { FameTier } from '@/data/types';

/**
 * The Liquipedia roster, used by Higher or Lower.
 *
 * Deliberately separate from `data/fortnite` and the `Dataset` class the other
 * nine games share. That dataset is the earlier Wikipedia import: 316 players
 * with full career histories, teammates and per-event results, and its
 * puzzle-eligibility rule is written around having those results. This one is
 * the Liquipedia dump — 5,678 players with a handle, a country, a birthday and
 * a career earnings figure, and no per-event rows at all — so it answers a
 * different question: "who exists, and what are they worth", which is exactly
 * what Higher or Lower asks.
 *
 * Generated by `scripts/build_liquipedia_roster.py`. Content from Liquipedia
 * (CC-BY-SA 3.0, see CREDITS.md); FNCS title counts are carried over from the
 * Wikipedia import, which is the only source that publishes them per player.
 */

/** One row exactly as `roster.json` stores it. */
interface RosterRow {
  /** Liquipedia page name — unique, so it is the identity. */
  id: string;
  /** Competitive handle, which is what the UI shows. */
  name: string;
  realName: string | null;
  /** ISO 3166-1 alpha-2, or null when the page lists no nationality. */
  country: string | null;
  countryName: string | null;
  /** Liquipedia's own region label, e.g. "North America". */
  region: string | null;
  birthDate: string | null;
  earnings: number;
  team: string | null;
  status: string | null;
  fncsWins: number;
  fameScore: number;
  tier: FameTier;
}

/** A roster row with the values the game reads off it. */
export interface RosterPlayer extends RosterRow {
  /** Age in whole years today, or null when no birth date is published. */
  age: number | null;
  /** False when Liquipedia publishes no prize money for the player. */
  earningsKnown: boolean;
  /** Always null here — the dump ships no headshots. Kept for `PlayerAvatar`. */
  photoUrl: null;
}

export interface RosterSource {
  name: string;
  url: string;
  license: string;
  licenseUrl: string;
  note: string;
}

interface RosterFile {
  generatedAt: string;
  source: RosterSource;
  players: RosterRow[];
}

function ageOn(birthDate: string | null, today: Date): number | null {
  if (!birthDate) return null;
  const born = new Date(birthDate);
  if (Number.isNaN(born.getTime())) return null;
  let age = today.getFullYear() - born.getFullYear();
  const months = today.getMonth() - born.getMonth();
  if (months < 0 || (months === 0 && today.getDate() < born.getDate())) age--;
  return age;
}

/**
 * Tier order to widen through when a pool is too small, closest first.
 *
 * Mirrors `Dataset`'s own fallback. FNCS titles are why it matters here: only
 * one player outside the top 20% of the fame ranking holds one, so Hard has to
 * borrow from Medium or that category cannot be played at all.
 */
const TIER_FALLBACK: Record<FameTier, FameTier[]> = {
  easy: ['easy', 'medium', 'hard'],
  medium: ['medium', 'easy', 'hard'],
  hard: ['hard', 'medium', 'easy'],
};

export class Roster {
  readonly players: RosterPlayer[];
  readonly source: RosterSource;
  /** Date the dump was turned into `roster.json`. */
  readonly generatedAt: string;

  private readonly byTier = new Map<FameTier, RosterPlayer[]>([
    ['easy', []],
    ['medium', []],
    ['hard', []],
  ]);

  constructor(file: RosterFile, today: Date = new Date()) {
    this.source = file.source;
    this.generatedAt = file.generatedAt;
    this.players = file.players.map((row) => ({
      ...row,
      age: ageOn(row.birthDate, today),
      earningsKnown: row.earnings > 0,
      photoUrl: null,
    }));
    for (const player of this.players) this.byTier.get(player.tier)?.push(player);
  }

  /**
   * The pool a game may draw from at one difficulty.
   *
   * `eligible` is the caller's own filter — Higher or Lower drops players with
   * no birth date from an Age run — and it runs per tier, because whether a
   * tier is big enough is a question about the players the game can actually
   * use. If that leaves fewer than `minimum`, the next-closest tier is folded
   * in rather than failing.
   */
  playersFor(
    tier: FameTier,
    options: { minimum?: number; eligible?: (players: RosterPlayer[]) => RosterPlayer[] } = {},
  ): RosterPlayer[] {
    const { minimum = 1, eligible } = options;
    const out: RosterPlayer[] = [];
    for (const step of TIER_FALLBACK[tier]) {
      const pool = this.byTier.get(step) ?? [];
      out.push(...(eligible ? eligible(pool) : pool));
      if (out.length >= minimum) break;
    }
    return out;
  }
}

let cached: Promise<Roster> | null = null;

/**
 * Loads (once) and indexes the roster.
 *
 * The JSON is imported dynamically so 1.3 MB of player rows stay out of the
 * app bundle and only download when someone opens the game.
 */
export function loadRoster(): Promise<Roster> {
  if (!cached) {
    cached = import('./roster.json').then((module) => new Roster(module.default as RosterFile));
  }
  return cached;
}
